fixtures:
  forge_modules:
    kmod:
      repo: "camptocamp/kmod"
      ref: "2.1.0"
    common:
      repo: "ghoneycutt/common"
      ref: "1.6.0"
    ssh:
      repo: "ghoneycutt/ssh"
      ref: "3.54.0"
    augeasproviders_core:
      repo: "herculesteam/augeasproviders_core"
      ref: "2.1.3"
    augeasproviders_sysctl:
      repo: "herculesteam/augeasproviders_sysctl"
      ref: "2.2.0"
    aide:
      repo: "lhinds/aide"
      ref: "1.0.2"
    concat:
      repo: "puppetlabs/concat"
      ref: "4.0.1"
    firewall:
      repo: "puppetlabs/firewall"
      ref: "1.9.0"
    limits:
      repo: "puppetlabs/limits"
      ref: "0.1.0"
    ntp:
      repo: "puppetlabs/ntp"
      ref: "6.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.17.1"
    rsyslog:
      repo: "saz/rsyslog"
      ref: "5.0.0"
